server:
  port: 8083  #tomcat 启动端口号

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mblog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 123456
  dubbo:
    application:
      name: service-provider
    base-package: com.csl.dubboproviders.service.Impl  # dubbo服务发布者实现类注解所在的包
    registry:
      address: 127.0.0.1                   # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0                    # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试