server:
  port: 8761
eureka:
  datacenter: trmap
  environment: product
  instance:
    hostname: localhost
  server:
    # \u5173\u95ED\u81EA\u6211\u4FDD\u62A4
    enable-self-preservation: false
    # \u6E05\u7406\u670D\u52A1\u5668
    eviction-interval-timer-in-ms: 5000
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

    register-with-eureka: false
    fetch-registry: false
spring:
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

